services:
  bankofmyhouse.api:
    image: ${DOCKER_REGISTRY-}bankofmyhouseapi
    build:
      context: .
      dockerfile: BankOfMyHouse.Server/Dockerfile
    container_name: bankofmyhouse.api
    environment:
        ConnectionStrings__DefaultConnection: "Host=postgres_db;Port=5432;Database=bankOfMyHouse;Username=myuser;Password=mypassword"
    networks:
       - bankofmyhouse_network    

  postgres_db:
    image: postgres:alpine
    container_name: postgres_db
    networks:
       - bankofmyhouse_network
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: bankOfMyHouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

networks:
  bankofmyhouse_network:
    name: bankofmyhouse_network
