services:
  bankofmyhouse.api:
    image: ${DOCKER_REGISTRY-}bankofmyhouseapi
    build:
      context: .
      dockerfile: BankOfMyHouse.Server/BankOfMyHouse.API/Dockerfile
    networks:
      - custom_network
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres_db;Port=5432;Database=bankOfMyHouse;Username=myuser;Password=mypassword"
   
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    networks:
      - custom_network
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: bankOfMyHouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

networks:
  custom_network: