services:
  bankofmyhouse.api:
    image: bankofmyhouseapi
    container_name: bankofmyhouse.api
    build:
      context: .
      dockerfile: BankOfMyHouse.Server/BankOfMyHouse.API/Dockerfile
    networks:
      - app_network
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres_db;Port=5432;Database=bankOfMyHouse;Username=myuser;Password=mypassword"
    depends_on:
      - postgres_db
    ports:
      - 57460:8080
       

  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    networks:
      - app_network
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: bankOfMyHouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: BankOfMyHouse.Client/Dockerfile
  #     target: development
  #   container_name: bankofmyhouse.client
  #   environment:
  #     - NODE_ENV=development    
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ./BankOfMyHouse.Client:/app
  #     - /app/node_modules
  #   depends_on:
  #     - bankofmyhouse.api
  #   networks:
  #     - app_network
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./BankOfMyHouse.Client/src
  #         target: /app/src
  #       - action: rebuild
  #         path: ./BankOfMyHouse.Client/package.json

volumes:
  postgres_data:
    driver: local

networks:
  app_network: